"""create stolen_items table with postgis

Revision ID: 43a7a1a6bd8e
Revises: 5567fa9e1fc3
Create Date: 2025-10-03 10:56:56.530300

"""
from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '43a7a1a6bd8e'
down_revision: str | Sequence[str] | None = '5567fa9e1fc3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stolen_items',
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('reporter_phone', sa.String(length=20), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('stolen_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('location_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('police_reference', sa.String(length=50), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    # NOTE: GeoAlchemy2 Column automatically creates idx_stolen_items_location_point
    # so we don't create it explicitly here to avoid conflicts
    op.create_index('ix_stolen_items_created_at', 'stolen_items', ['created_at'], unique=False)
    op.create_index('ix_stolen_items_reporter_phone', 'stolen_items', ['reporter_phone'], unique=False)
    op.create_index('ix_stolen_items_type_status', 'stolen_items', ['item_type', 'status'], unique=False)
    # NOTE: Do not drop PostGIS tables (spatial_ref_sys, topology, layer)
    # These are system tables created by PostGIS extensions
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Do not recreate PostGIS tables - they're managed by PostGIS extensions
    op.drop_index('ix_stolen_items_type_status', table_name='stolen_items')
    op.drop_index('ix_stolen_items_reporter_phone', table_name='stolen_items')
    op.drop_index('ix_stolen_items_created_at', table_name='stolen_items')
    # NOTE: idx_stolen_items_location_point is auto-dropped with the table
    op.drop_table('stolen_items')
    # ### end Alembic commands ###
