name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test & Quality Checks
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:18-3.6
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin_password
          POSTGRES_DB: isitstolen
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:8.2-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch base branch for coverage comparison
        if: github.event_name == 'pull_request'
        run: git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-3.13-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            pip-${{ runner.os }}-3.13-

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-3.13-${{ hashFiles('**/poetry.lock') }}

      - name: Cache MyPy
        uses: actions/cache@v4
        with:
          path: .mypy_cache
          key: mypy-${{ runner.os }}-3.13-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('**/*.py') }}
          restore-keys: |
            mypy-${{ runner.os }}-3.13-${{ hashFiles('**/poetry.lock') }}-
            mypy-${{ runner.os }}-3.13-

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Install project
        run: poetry install --no-interaction

      - name: Run linting
        run: poetry run ruff check src tests

      - name: Run formatting check
        run: poetry run ruff format src tests --check

      - name: Run type checking
        run: poetry run mypy src

      - name: Run unit tests
        env:
          DATABASE_URL: postgresql://admin:admin_password@localhost:5432/isitstolen
          REDIS_URL: redis://localhost:6379
        run: poetry run pytest tests/unit -m unit --cov-report=xml --cov-report=term

      - name: Upload unit test coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: unit
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

      - name: Run integration tests
        env:
          DATABASE_URL: postgresql://admin:admin_password@localhost:5432/isitstolen
          REDIS_URL: redis://localhost:6379
        run: poetry run pytest tests/integration -m integration --cov-report=xml --cov-report=term --cov-append
        continue-on-error: true

      - name: Upload integration test coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: integration
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
        continue-on-error: true

      - name: Run e2e tests
        env:
          DATABASE_URL: postgresql://admin:admin_password@localhost:5432/isitstolen
          REDIS_URL: redis://localhost:6379
        run: poetry run pytest tests/e2e -m e2e --cov-report=xml --cov-report=term --cov-append
        continue-on-error: true

      - name: Upload e2e test coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.xml
          flags: e2e
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
        continue-on-error: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
