name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sundays at midnight UTC

jobs:
  dependency-scan:
    name: Dependency Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.4
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction --only main,dev

      - name: Upgrade pip to latest version
        run: poetry run pip install --upgrade pip

      - name: Run Safety to check for known vulnerabilities (using legacy check for CI)
        run: |
          # Safety scan requires authentication in v3+, using legacy check command for CI
          poetry run safety check --output text || echo "⚠️ Safety found vulnerabilities"
        continue-on-error: true

      - name: Run pip-audit as additional check
        run: |
          poetry run pip install pip-audit
          # Note: pip 25.2 has GHSA-4xh5-x5gv-qwph vulnerability - fix planned for 25.3
          # This is a known issue in pip itself, not our dependencies
          poetry run pip-audit --desc --skip-editable --ignore-vuln GHSA-4xh5-x5gv-qwph || echo "⚠️ pip-audit found vulnerabilities"
        continue-on-error: true

  code-security-scan:
    name: Static Code Security Analysis (Bandit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.4
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction --only dev

      - name: Run Bandit security linter
        run: poetry run bandit -r src/ -f json -o bandit-report.json
        continue-on-error: true

      - name: Display Bandit results
        if: always()
        run: poetry run bandit -r src/ -f screen

  secret-scan:
    name: Secret Detection
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Run detect-secrets
        run: |
          pip install detect-secrets
          detect-secrets scan --all-files --force-use-all-plugins \
            --exclude-files '\.secrets\.baseline$' \
            --exclude-files 'poetry\.lock$' \
            --exclude-files '\.git/'

  docker-scan:
    name: Docker Image Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Build Docker image
        run: docker build -t is-it-stolen:latest .

      - name: Run Trivy scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'is-it-stolen:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'  # Don't fail build on vulnerabilities

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: python
          queries: security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
